[package]
name = "bcachefs_rs"
version = "0.1.0"
edition = "2021"
authors = ["Stijn Tintel <stijn@linux-ipv6.be>"]

[lib]
name = "bcachefs_rs"
crate-type = ["cdylib"]

[dependencies]
libc = "0.2"
rpassword = "7.2"
zeroize = "1.5"
